apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: bank # Replace with your namespace
  labels:
    app: payment-gateway
spec:
  replicas: 3 # Number of replicas
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
      - name: payment-gateway-container
        image: uma/payment-gateway:latest # Replace with your image
        ports:
        - containerPort: 8081 # Replace with the port your app listens on
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health # Replace with your health endpoint
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health # Replace with your health endpoint
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  namespace: bank  # Use the same namespace as your deployment
spec:
  selector:
    app: payment-gateway  # Matches the label in your deployment's pod template
  ports:
    - protocol: TCP
      port: 80             # Port exposed by the service
      targetPort: 8081     # Port where your application listens inside the pod
  type: ClusterIP        # Default service type; can also be LoadBalancer or NodePort

